name: Run unit test

on: 
  push:
    branches:
      - main
    paths: 
      - 'week-5/**'

jobs: 
  test: 
    runs-on: ubuntu-latest

    steps: 
     - name: Checkout code 
       uses: actions/checkout@v2

     - name: Set up Node.js
       uses: actions/setup-node@v4
       with:
         node-version: '20'

     - name: Install dependencies
       run: cd week-5 && npm install
     - name: Run tests
       run: cd week-5 &&s npm test